// Dados fixos do MVP: habilidades (DAG de pré-requisitos), alunos de exemplo
// e o banco de questões (8 por habilidade: 3 de dificuldade 1, 3 de 2 e 2 de 3).
// A `dica` só aparece para a criança quando o motor aciona o scaffolding.
//
// O grafo segue o rascunho de senso numérico do CLAUDE.md e ainda precisa da
// validação dos conteudistas. A ordem do array é topológica: o teste rápido e a
// zona proximal percorrem as habilidades nesta ordem.
//
// O frontend desenha o enunciado como material concreto (lib/representacao.js):
// dados (⚀–⚅), figuras repetidas, sequências, contas "a + b = ?" e "a + ? = c",
// e quadros de dez no apoio. Evite "mais" em frases com dois números que não são
// soma: o parser lê isso como adição.

export const HABILIDADES = [
  {
    id: 'subitizacao',
    nome: 'Subitização',
    pre_requisitos: [],
  },
  {
    id: 'contagem_ate_10',
    nome: 'Contagem até 10',
    pre_requisitos: [],
  },
  {
    id: 'numerais_ate_20',
    nome: 'Numerais até 20',
    pre_requisitos: [],
  },
  {
    id: 'numero_quantidade',
    nome: 'Número e quantidade',
    pre_requisitos: ['subitizacao', 'contagem_ate_10', 'numerais_ate_20'],
  },
  {
    id: 'comparacao',
    nome: 'Comparação de quantidades',
    pre_requisitos: ['numero_quantidade'],
  },
  {
    id: 'composicao_ate_10',
    nome: 'Composição até 10',
    pre_requisitos: ['numero_quantidade'],
  },
  {
    id: 'adicao_ate_10',
    nome: 'Adição até 10',
    pre_requisitos: ['composicao_ate_10'],
  },
  {
    id: 'subtracao_ate_10',
    nome: 'Subtração até 10',
    pre_requisitos: ['adicao_ate_10'],
  },
  {
    id: 'valor_posicional',
    nome: 'Valor posicional',
    pre_requisitos: ['adicao_ate_10', 'subtracao_ate_10'],
  },
  {
    id: 'adicao_com_reagrupamento',
    nome: 'Adição até 20',
    pre_requisitos: ['valor_posicional'],
  },
  {
    id: 'subtracao_com_reagrupamento',
    nome: 'Subtração até 20',
    pre_requisitos: ['valor_posicional'],
  },
];

export const ALUNOS = [
  { id: 1, nome: 'Ana' },
  { id: 2, nome: 'Bruno' },
  { id: 3, nome: 'Clara' },
  { id: 4, nome: 'Davi' },
  { id: 5, nome: 'Elisa' },
];

export const QUESTOES = [
  // ---------- subitizacao ----------
  // Subitização: reconhecer quantidades pequenas pelo desenho, sem contar um a um.
  // Sem tempo de exibição na tela, não dá para impedir a contagem; os padrões de
  // dado favorecem o reconhecimento. O nível 3 junta dois dados (subitização conceitual).
  {
    id: 'subit_1',
    habilidade: 'subitizacao',
    dificuldade: 1,
    enunciado: 'Sem contar um por um: quantos pontos tem o dado? ⚁',
    alternativas: ['1', '2', '3', '4'],
    resposta_correta: '2',
    dica: 'Dois pontos fazem uma linha de canto a canto. Olhe o desenho inteiro.',
  },
  {
    id: 'subit_2',
    habilidade: 'subitizacao',
    dificuldade: 1,
    enunciado: 'Sem contar um por um: quantos pontos tem o dado? ⚂',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '3',
    dica: 'Três pontos fazem uma linha torta: um em cada canto e um no meio.',
  },
  {
    id: 'subit_3',
    habilidade: 'subitizacao',
    dificuldade: 1,
    enunciado: 'Sem contar um por um: quantos pontos tem o dado? ⚃',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '4',
    dica: 'Quatro pontos: um em cada canto do dado, como um quadrado.',
  },
  {
    id: 'subit_4',
    habilidade: 'subitizacao',
    dificuldade: 2,
    enunciado: 'Sem contar um por um: quantos pontos tem o dado? ⚄',
    alternativas: ['4', '5', '6', '7'],
    resposta_correta: '5',
    dica: 'É o desenho do 4, um ponto em cada canto, com mais um no meio.',
  },
  {
    id: 'subit_5',
    habilidade: 'subitizacao',
    dificuldade: 2,
    enunciado: 'Sem contar um por um: quantos pontos tem o dado? ⚅',
    alternativas: ['4', '5', '6', '7'],
    resposta_correta: '6',
    dica: 'São duas colunas de três pontos. Três e três.',
  },
  {
    id: 'subit_6',
    habilidade: 'subitizacao',
    dificuldade: 2,
    enunciado: 'Quantos pontos nos dois dados juntos? ⚁ ⚁',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '4',
    dica: 'Cada dado tem 2 pontos. Dois e dois.',
  },
  {
    id: 'subit_7',
    habilidade: 'subitizacao',
    dificuldade: 3,
    enunciado: 'Quantos pontos nos dois dados juntos? ⚃ ⚂',
    alternativas: ['6', '7', '8', '9'],
    resposta_correta: '7',
    dica: 'Reconheça o 4 no primeiro dado e continue contando os 3 do outro: 5, 6, 7.',
  },
  {
    id: 'subit_8',
    habilidade: 'subitizacao',
    dificuldade: 3,
    enunciado: 'Quantos pontos nos dois dados juntos? ⚄ ⚃',
    alternativas: ['8', '9', '10', '11'],
    resposta_correta: '9',
    dica: 'Reconheça o 5 no primeiro dado e continue contando os 4 do outro: 6, 7, 8, 9.',
  },
  // ---------- contagem_ate_10 ----------
  // Contagem: contar objetos e a sequência numérica, para a frente e para trás.
  {
    id: 'cont_1',
    habilidade: 'contagem_ate_10',
    dificuldade: 1,
    enunciado: 'Quantas bolinhas você vê?  🔵 🔵 🔵',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '3',
    dica: 'Toque em cada bolinha com o dedo e diga um número: 1, 2, 3…',
  },
  {
    id: 'cont_2',
    habilidade: 'contagem_ate_10',
    dificuldade: 1,
    enunciado: 'Conte os patinhos:  🦆 🦆 🦆 🦆 🦆',
    alternativas: ['4', '5', '6', '7'],
    resposta_correta: '5',
    dica: 'Aponte para cada patinho uma vez só, contando em voz alta.',
  },
  {
    id: 'cont_3',
    habilidade: 'contagem_ate_10',
    dificuldade: 2,
    enunciado: 'Qual número vem depois do 6?',
    alternativas: ['5', '6', '7', '8'],
    resposta_correta: '7',
    dica: 'Conte desde o 1 até chegar no 6. Qual número você diria em seguida?',
  },
  {
    id: 'cont_4',
    habilidade: 'contagem_ate_10',
    dificuldade: 2,
    enunciado: 'Complete a sequência: 3, 4, 5, ___, 7',
    alternativas: ['2', '6', '8', '9'],
    resposta_correta: '6',
    dica: 'Leia a sequência em voz alta: 3, 4, 5… qual vem antes do 7?',
  },
  {
    id: 'cont_5',
    habilidade: 'contagem_ate_10',
    dificuldade: 3,
    enunciado: 'Contando de trás para frente: 10, 9, 8, ___',
    alternativas: ['6', '7', '9', '11'],
    resposta_correta: '7',
    dica: 'Contar para trás é andar um passo para trás: 10, 9, 8 e…?',
  },
  {
    id: 'cont_6',
    habilidade: 'contagem_ate_10',
    dificuldade: 1,
    enunciado: 'Quantas flores você vê?  🌼 🌼 🌼 🌼',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '4',
    dica: 'Toque em cada flor uma vez só e vá contando: 1, 2, 3…',
  },
  {
    id: 'cont_7',
    habilidade: 'contagem_ate_10',
    dificuldade: 2,
    enunciado: 'Conte os peixinhos:  🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟',
    alternativas: ['6', '7', '8', '9'],
    resposta_correta: '8',
    dica: 'Comece por uma ponta e toque em cada peixinho, sem pular nenhum.',
  },
  {
    id: 'cont_8',
    habilidade: 'contagem_ate_10',
    dificuldade: 3,
    enunciado: 'Qual número vem antes do 9?',
    alternativas: ['7', '8', '9', '10'],
    resposta_correta: '8',
    dica: 'Conte até o 9 bem devagar: qual número você falou logo antes dele?',
  },
  // ---------- numerais_ate_20 ----------
  // Numerais: ligar o nome do número ao jeito de escrever. As alternativas trazem
  // as trocas comuns (12 e 21, 17 e 71).
  {
    id: 'num_1',
    habilidade: 'numerais_ate_20',
    dificuldade: 1,
    enunciado: 'Qual destes é o número sete?',
    alternativas: ['1', '7', '4', '9'],
    resposta_correta: '7',
    dica: 'O sete tem um tracinho em cima e desce inclinado.',
  },
  {
    id: 'num_2',
    habilidade: 'numerais_ate_20',
    dificuldade: 1,
    enunciado: 'Qual destes é o número três?',
    alternativas: ['3', '8', '5', '6'],
    resposta_correta: '3',
    dica: 'O três parece duas barriguinhas abertas para o lado esquerdo.',
  },
  {
    id: 'num_3',
    habilidade: 'numerais_ate_20',
    dificuldade: 1,
    enunciado: 'Qual destes é o número dez?',
    alternativas: ['1', '0', '10', '11'],
    resposta_correta: '10',
    dica: 'O dez tem dois algarismos: o 1 e, logo depois, o 0.',
  },
  {
    id: 'num_4',
    habilidade: 'numerais_ate_20',
    dificuldade: 2,
    enunciado: 'Qual destes é o número doze?',
    alternativas: ['21', '12', '2', '20'],
    resposta_correta: '12',
    dica: 'Doze é dez e mais dois. O 1 da dezena vem primeiro, depois o 2.',
  },
  {
    id: 'num_5',
    habilidade: 'numerais_ate_20',
    dificuldade: 2,
    enunciado: 'Qual destes é o número quinze?',
    alternativas: ['51', '15', '5', '50'],
    resposta_correta: '15',
    dica: 'Quinze é dez e mais cinco. O 1 vem primeiro, depois o 5.',
  },
  {
    id: 'num_6',
    habilidade: 'numerais_ate_20',
    dificuldade: 2,
    enunciado: 'Qual destes é o número onze?',
    alternativas: ['1', '11', '10', '12'],
    resposta_correta: '11',
    dica: 'Onze é dez e mais um: dois algarismos 1, um do lado do outro.',
  },
  {
    id: 'num_7',
    habilidade: 'numerais_ate_20',
    dificuldade: 3,
    enunciado: 'Qual destes é o número dezessete?',
    alternativas: ['71', '17', '7', '70'],
    resposta_correta: '17',
    dica: 'Dezessete começa com "dez": o 1 vem primeiro, depois o 7.',
  },
  {
    id: 'num_8',
    habilidade: 'numerais_ate_20',
    dificuldade: 3,
    enunciado: 'Qual destes é o número vinte?',
    alternativas: ['2', '12', '20', '22'],
    resposta_correta: '20',
    dica: 'Vinte são duas dezenas: o 2 e depois o 0.',
  },
  // ---------- numero_quantidade ----------
  // Número e quantidade: o número diz quantos há (cardinalidade) e não muda se as
  // coisas trocam de lugar (conservação).
  {
    id: 'nq_1',
    habilidade: 'numero_quantidade',
    dificuldade: 1,
    enunciado: 'Em qual grupo há 3 estrelas?',
    alternativas: ['⭐⭐', '⭐⭐⭐', '⭐⭐⭐⭐', '⭐'],
    resposta_correta: '⭐⭐⭐',
    dica: 'Conte as estrelas de cada grupo e procure o grupo que termina no 3.',
  },
  {
    id: 'nq_2',
    habilidade: 'numero_quantidade',
    dificuldade: 1,
    enunciado: 'Em qual grupo há 2 maçãs?',
    alternativas: ['🍎', '🍎🍎', '🍎🍎🍎', '🍎🍎🍎🍎'],
    resposta_correta: '🍎🍎',
    dica: 'Procure o grupo com uma maçã e mais outra.',
  },
  {
    id: 'nq_3',
    habilidade: 'numero_quantidade',
    dificuldade: 1,
    enunciado: 'Qual número diz quantas bolas há?  🏀 🏀 🏀 🏀',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '4',
    dica: 'Conte as bolas. O último número que você falar é quantas bolas há.',
  },
  {
    id: 'nq_4',
    habilidade: 'numero_quantidade',
    dificuldade: 2,
    enunciado: 'A Lia contou os carrinhos: 1, 2, 3, 4, 5. Quantos carrinhos ela tem?',
    alternativas: ['1', '4', '5', '6'],
    resposta_correta: '5',
    dica: 'Quando a gente conta, o último número falado diz quantos são.',
  },
  {
    id: 'nq_5',
    habilidade: 'numero_quantidade',
    dificuldade: 2,
    enunciado: 'Em qual grupo há 5 bolinhas?',
    alternativas: ['🟢🟢🟢🟢', '🟢🟢🟢🟢🟢', '🟢🟢🟢', '🟢🟢🟢🟢🟢🟢'],
    resposta_correta: '🟢🟢🟢🟢🟢',
    dica: 'Conte cada grupo com o dedo e pare no que termina no 5.',
  },
  {
    id: 'nq_6',
    habilidade: 'numero_quantidade',
    dificuldade: 2,
    enunciado: 'Qual número diz quantas joaninhas há?  🐞 🐞 🐞 🐞 🐞 🐞',
    alternativas: ['5', '6', '7', '8'],
    resposta_correta: '6',
    dica: 'Toque em cada joaninha contando. O último número é a resposta.',
  },
  {
    id: 'nq_7',
    habilidade: 'numero_quantidade',
    dificuldade: 3,
    enunciado:
      'Havia 7 lápis em fila. Alguém espalhou os lápis pela mesa, sem tirar nenhum. Quantos lápis há agora?',
    alternativas: ['5', '6', '7', '8'],
    resposta_correta: '7',
    dica: 'Ninguém tirou nem colocou lápis. Mudar de lugar não muda quantos são.',
  },
  {
    id: 'nq_8',
    habilidade: 'numero_quantidade',
    dificuldade: 3,
    enunciado:
      'Pedro e Ana têm 4 figurinhas cada. As de Pedro estão juntinhas e as de Ana, espalhadas. Quem tem mais?',
    alternativas: ['Pedro', 'Ana', 'Iguais'],
    resposta_correta: 'Iguais',
    dica: 'Os dois têm 4. Espalhar as figurinhas não muda a quantidade.',
  },
  // ---------- comparacao ----------
  // Comparação: maior, menor e ordem.
  {
    id: 'comp_1',
    habilidade: 'comparacao',
    dificuldade: 1,
    enunciado: 'Qual é o maior número: 2 ou 5?',
    alternativas: ['2', '5'],
    resposta_correta: '5',
    dica: 'Conte a partir do 1. O número que aparece por último é o maior.',
  },
  {
    id: 'comp_2',
    habilidade: 'comparacao',
    dificuldade: 1,
    enunciado: 'Qual é o menor número: 7 ou 4?',
    alternativas: ['7', '4'],
    resposta_correta: '4',
    dica: 'Conte a partir do 1. O número que aparece primeiro é o menor.',
  },
  {
    id: 'comp_3',
    habilidade: 'comparacao',
    dificuldade: 1,
    enunciado: 'Em qual grupo há mais bolinhas?',
    alternativas: ['🔵🔵', '🔵🔵🔵🔵'],
    resposta_correta: '🔵🔵🔵🔵',
    dica: 'Ligue uma bolinha de um grupo a uma do outro. Onde sobrar bolinha, há mais.',
  },
  {
    id: 'comp_4',
    habilidade: 'comparacao',
    dificuldade: 2,
    enunciado: 'Ana tem 6 balas e Leo tem 9 balas. Quem tem a maior quantidade?',
    alternativas: ['Ana', 'Leo'],
    resposta_correta: 'Leo',
    dica: 'Compare o 6 e o 9: qual vem depois quando a gente conta?',
  },
  {
    id: 'comp_5',
    habilidade: 'comparacao',
    dificuldade: 2,
    enunciado: 'Qual é o maior número: 12 ou 9?',
    alternativas: ['12', '9'],
    resposta_correta: '12',
    dica: 'O 12 tem uma dezena inteira. O 9 nem chega a uma dezena.',
  },
  {
    id: 'comp_6',
    habilidade: 'comparacao',
    dificuldade: 2,
    enunciado: 'Qual é o menor número: 15 ou 11?',
    alternativas: ['15', '11'],
    resposta_correta: '11',
    dica: 'Os dois começam com uma dezena. Compare as unidades: 5 e 1.',
  },
  {
    id: 'comp_7',
    habilidade: 'comparacao',
    dificuldade: 3,
    enunciado: 'Dos números 9, 4 e 6, qual fica no meio quando colocados em ordem?',
    alternativas: ['9', '4', '6'],
    resposta_correta: '6',
    dica: 'Coloque do menor para o maior: primeiro o 4, depois…',
  },
  {
    id: 'comp_8',
    habilidade: 'comparacao',
    dificuldade: 3,
    enunciado: 'Qual número está mais perto do 10: 7 ou 12?',
    alternativas: ['7', '12'],
    resposta_correta: '12',
    dica: 'Do 7 até o 10 são 3 passos. Do 10 até o 12 são quantos?',
  },
  // ---------- composicao_ate_10 ----------
  // Composição e decomposição: quanto falta e que pares formam um número.
  {
    id: 'compo_1',
    habilidade: 'composicao_ate_10',
    dificuldade: 1,
    enunciado: 'Tenho 8 fichas. Quantas faltam para completar 10?',
    alternativas: ['1', '2', '3', '4'],
    resposta_correta: '2',
    dica: 'Conte a partir do 8 até chegar no 10: 9, 10. Quantos passos?',
  },
  {
    id: 'compo_2',
    habilidade: 'composicao_ate_10',
    dificuldade: 1,
    enunciado: 'Tenho 9 fichas. Quantas faltam para completar 10?',
    alternativas: ['1', '2', '3', '9'],
    resposta_correta: '1',
    dica: 'Do 9 para o 10 é só um passo.',
  },
  {
    id: 'compo_3',
    habilidade: 'composicao_ate_10',
    dificuldade: 1,
    enunciado: '2 + ? = 4',
    alternativas: ['1', '2', '3', '4'],
    resposta_correta: '2',
    dica: 'Mostre 2 dedos. Quantos você precisa levantar para ficar com 4?',
  },
  {
    id: 'compo_4',
    habilidade: 'composicao_ate_10',
    dificuldade: 2,
    enunciado: 'Tenho 6 fichas. Quantas faltam para completar 10?',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '4',
    dica: 'Conte a partir do 6 até o 10 nos dedos: 7, 8, 9, 10.',
  },
  {
    id: 'compo_5',
    habilidade: 'composicao_ate_10',
    dificuldade: 2,
    enunciado: '3 + ? = 7',
    alternativas: ['3', '4', '5', '10'],
    resposta_correta: '4',
    dica: 'Comece no 3 e conte até chegar no 7. Quantos números você falou?',
  },
  {
    id: 'compo_6',
    habilidade: 'composicao_ate_10',
    dificuldade: 2,
    enunciado: 'Tenho 3 fichas. Quantas faltam para completar 10?',
    alternativas: ['6', '7', '8', '13'],
    resposta_correta: '7',
    dica: 'Mostre 3 dedos. Quantos dedos ficaram abaixados?',
  },
  {
    id: 'compo_7',
    habilidade: 'composicao_ate_10',
    dificuldade: 3,
    enunciado: '4 + ? = 9',
    alternativas: ['4', '5', '6', '13'],
    resposta_correta: '5',
    dica: 'Comece no 4 e conte até o 9: 5, 6, 7, 8, 9.',
  },
  {
    id: 'compo_8',
    habilidade: 'composicao_ate_10',
    dificuldade: 3,
    enunciado: 'Qual dupla forma 10?',
    alternativas: ['6 e 3', '7 e 3', '5 e 4', '8 e 1'],
    resposta_correta: '7 e 3',
    dica: 'Some cada dupla nos dedos. Qual delas usa as duas mãos inteiras?',
  },
  // ---------- adicao_ate_10 ----------
  {
    id: 'soma_1',
    habilidade: 'adicao_ate_10',
    dificuldade: 1,
    enunciado: '2 + 1 = ?',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '3',
    dica: 'Mostre 2 dedos, depois levante mais 1. Quantos dedos ficaram?',
  },
  {
    id: 'soma_2',
    habilidade: 'adicao_ate_10',
    dificuldade: 1,
    enunciado: '3 + 2 = ?',
    alternativas: ['4', '5', '6', '7'],
    resposta_correta: '5',
    dica: 'Comece no 3 e conte mais 2 para a frente: 4, 5.',
  },
  {
    id: 'soma_3',
    habilidade: 'adicao_ate_10',
    dificuldade: 2,
    enunciado: '4 + 3 = ?',
    alternativas: ['6', '7', '8', '9'],
    resposta_correta: '7',
    dica: 'Guarde o 4 na cabeça e conte mais 3 nos dedos: 5, 6, 7.',
  },
  {
    id: 'soma_4',
    habilidade: 'adicao_ate_10',
    dificuldade: 2,
    enunciado: '5 + 4 = ?',
    alternativas: ['8', '9', '10', '11'],
    resposta_correta: '9',
    dica: 'Comece pelo número maior, o 5, e conte mais 4 para a frente.',
  },
  {
    id: 'soma_5',
    habilidade: 'adicao_ate_10',
    dificuldade: 3,
    enunciado: 'Ana tinha 6 figurinhas e ganhou mais 4. Com quantas figurinhas ela ficou?',
    alternativas: ['8', '9', '10', '12'],
    resposta_correta: '10',
    dica: 'Ela já tinha 6. Conte mais 4 a partir do 6.',
  },
  {
    id: 'soma_6',
    habilidade: 'adicao_ate_10',
    dificuldade: 1,
    enunciado: '1 + 4 = ?',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '5',
    dica: 'Comece pelo 4, que é o maior, e conte mais 1.',
  },
  {
    id: 'soma_7',
    habilidade: 'adicao_ate_10',
    dificuldade: 2,
    enunciado: '6 + 2 = ?',
    alternativas: ['7', '8', '9', '10'],
    resposta_correta: '8',
    dica: 'Guarde o 6 na cabeça e conte mais 2: 7, 8.',
  },
  {
    id: 'soma_8',
    habilidade: 'adicao_ate_10',
    dificuldade: 3,
    enunciado: 'Na árvore havia 3 passarinhos e chegaram mais 5. Quantos passarinhos há agora?',
    alternativas: ['7', '8', '9', '10'],
    resposta_correta: '8',
    dica: 'Comece pelo 5 e conte mais 3: 6, 7, 8.',
  },
  // ---------- subtracao_ate_10 ----------
  {
    id: 'sub_1',
    habilidade: 'subtracao_ate_10',
    dificuldade: 1,
    enunciado: '3 − 1 = ?',
    alternativas: ['1', '2', '3', '4'],
    resposta_correta: '2',
    dica: 'Mostre 3 dedos e abaixe 1. Quantos ficaram levantados?',
  },
  {
    id: 'sub_2',
    habilidade: 'subtracao_ate_10',
    dificuldade: 1,
    enunciado: '5 − 2 = ?',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '3',
    dica: 'Desenhe 5 risquinhos e risque 2. Quantos sobraram?',
  },
  {
    id: 'sub_3',
    habilidade: 'subtracao_ate_10',
    dificuldade: 2,
    enunciado: '8 − 3 = ?',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '5',
    dica: 'Comece no 8 e conte 3 para trás: 7, 6, 5.',
  },
  {
    id: 'sub_4',
    habilidade: 'subtracao_ate_10',
    dificuldade: 2,
    enunciado: '9 − 4 = ?',
    alternativas: ['4', '5', '6', '7'],
    resposta_correta: '5',
    dica: 'Quanto falta do 4 para chegar no 9? Conte para a frente a partir do 4.',
  },
  {
    id: 'sub_5',
    habilidade: 'subtracao_ate_10',
    dificuldade: 3,
    enunciado: 'Tinha 10 bolinhas na caixa e 6 caíram no chão. Quantas ficaram na caixa?',
    alternativas: ['3', '4', '5', '6'],
    resposta_correta: '4',
    dica: 'Eram 10 e 6 saíram. Conte para trás 6 vezes a partir do 10.',
  },
  {
    id: 'sub_6',
    habilidade: 'subtracao_ate_10',
    dificuldade: 1,
    enunciado: '4 − 1 = ?',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '3',
    dica: 'Mostre 4 dedos e abaixe 1. Quantos ficaram?',
  },
  {
    id: 'sub_7',
    habilidade: 'subtracao_ate_10',
    dificuldade: 2,
    enunciado: '7 − 4 = ?',
    alternativas: ['2', '3', '4', '5'],
    resposta_correta: '3',
    dica: 'Quanto falta do 4 para chegar no 7? Conte: 5, 6, 7.',
  },
  {
    id: 'sub_8',
    habilidade: 'subtracao_ate_10',
    dificuldade: 3,
    enunciado: 'Bia tinha 9 balas e comeu 5. Quantas balas sobraram?',
    alternativas: ['3', '4', '5', '14'],
    resposta_correta: '4',
    dica: 'Eram 9 e saíram 5. Conte 5 para trás a partir do 9.',
  },
  // ---------- valor_posicional ----------
  // Valor posicional: a dezena como um grupo de 10. O apoio mostra o número em
  // quadros de dez, um quadro cheio para cada dezena.
  {
    id: 'vp_1',
    habilidade: 'valor_posicional',
    dificuldade: 1,
    enunciado: 'Uma dezena é igual a quantas unidades?',
    alternativas: ['1', '5', '10', '100'],
    resposta_correta: '10',
    dica: 'Uma dezena é um quadro de dez cheio. Conte as casas.',
  },
  {
    id: 'vp_2',
    habilidade: 'valor_posicional',
    dificuldade: 1,
    enunciado: 'Quantas dezenas tem o número 13?',
    alternativas: ['1', '3', '10', '13'],
    resposta_correta: '1',
    dica: 'O 13 é um quadro de dez cheio e mais 3 fichas. Quantos quadros cheios?',
  },
  {
    id: 'vp_3',
    habilidade: 'valor_posicional',
    dificuldade: 1,
    enunciado: 'O número 16 tem 1 dezena e quantas unidades?',
    alternativas: ['1', '6', '10', '16'],
    resposta_correta: '6',
    dica: 'Encha um quadro de dez. Quantas fichas sobram fora dele?',
  },
  {
    id: 'vp_4',
    habilidade: 'valor_posicional',
    dificuldade: 2,
    enunciado: '1 dezena e 4 unidades formam qual número?',
    alternativas: ['14', '41', '5', '104'],
    resposta_correta: '14',
    dica: 'Uma dezena é 10. Dez e mais quatro é…',
  },
  {
    id: 'vp_5',
    habilidade: 'valor_posicional',
    dificuldade: 2,
    enunciado: '1 dezena e 9 unidades formam qual número?',
    alternativas: ['19', '91', '10', '109'],
    resposta_correta: '19',
    dica: 'Comece no 10 e conte mais 9.',
  },
  {
    id: 'vp_6',
    habilidade: 'valor_posicional',
    dificuldade: 2,
    enunciado: 'No número 18, quantas unidades sobram além da dezena?',
    alternativas: ['1', '8', '10', '18'],
    resposta_correta: '8',
    dica: 'Tire o quadro de dez cheio do 18. Quantas fichas ficam?',
  },
  {
    id: 'vp_7',
    habilidade: 'valor_posicional',
    dificuldade: 3,
    enunciado: 'No número 15, quanto vale o algarismo 1?',
    alternativas: ['1', '5', '10', '15'],
    resposta_correta: '10',
    dica: 'O 1 do 15 está no lugar das dezenas: ele vale um quadro de dez inteiro.',
  },
  {
    id: 'vp_8',
    habilidade: 'valor_posicional',
    dificuldade: 3,
    enunciado: 'Qual número tem 2 dezenas e 0 unidades?',
    alternativas: ['2', '20', '200', '02'],
    resposta_correta: '20',
    dica: 'Dois quadros de dez cheios e nenhuma ficha sobrando.',
  },
  // ---------- adicao_com_reagrupamento ----------
  // Adição até 20, passando do 10: completar o 10 primeiro.
  {
    id: 'reagr_1',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 1,
    enunciado: '7 + 5 = ?',
    alternativas: ['11', '12', '13', '14'],
    resposta_correta: '12',
    dica: 'Complete o 10 primeiro: 7 + 3 = 10. Sobram 2 do 5. Quanto é 10 + 2?',
  },
  {
    id: 'reagr_2',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 1,
    enunciado: '8 + 4 = ?',
    alternativas: ['10', '11', '12', '13'],
    resposta_correta: '12',
    dica: 'Complete o 10 primeiro: 8 + 2 = 10. Sobram 2 do 4. Quanto é 10 + 2?',
  },
  {
    id: 'reagr_3',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 2,
    enunciado: '9 + 6 = ?',
    alternativas: ['14', '15', '16', '17'],
    resposta_correta: '15',
    dica: 'Complete o 10 primeiro: 9 + 1 = 10. Sobram 5 do 6. Quanto é 10 + 5?',
  },
  {
    id: 'reagr_4',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 2,
    enunciado: '8 + 7 = ?',
    alternativas: ['13', '14', '15', '16'],
    resposta_correta: '15',
    dica: 'Complete o 10 primeiro: 8 + 2 = 10. Sobram 5 do 7. Quanto é 10 + 5?',
  },
  {
    id: 'reagr_5',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 3,
    enunciado: 'Lucas tinha 9 bolinhas de gude e ganhou mais 8. Quantas bolinhas ele tem agora?',
    alternativas: ['15', '16', '17', '18'],
    resposta_correta: '17',
    dica: 'Complete o 10 primeiro: 9 + 1 = 10. Sobram 7 do 8. Quanto é 10 + 7?',
  },
  {
    id: 'reagr_6',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 1,
    enunciado: '9 + 2 = ?',
    alternativas: ['10', '11', '12', '13'],
    resposta_correta: '11',
    dica: 'Complete o 10 primeiro: 9 + 1 = 10. Sobra 1 do 2. Quanto é 10 + 1?',
  },
  {
    id: 'reagr_7',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 2,
    enunciado: '6 + 7 = ?',
    alternativas: ['12', '13', '14', '15'],
    resposta_correta: '13',
    dica: 'Complete o 10 primeiro: 7 + 3 = 10. Sobram 3 do 6. Quanto é 10 + 3?',
  },
  {
    id: 'reagr_8',
    habilidade: 'adicao_com_reagrupamento',
    dificuldade: 3,
    enunciado: 'Num ônibus havia 8 pessoas e chegaram mais 6. Quantas pessoas há no ônibus?',
    alternativas: ['12', '13', '14', '15'],
    resposta_correta: '14',
    dica: 'Complete o 10 primeiro: 8 + 2 = 10. Sobram 4 do 6. Quanto é 10 + 4?',
  },
  // ---------- subtracao_com_reagrupamento ----------
  // Subtração até 20, passando do 10: tirar até chegar no 10 primeiro.
  {
    id: 'subr_1',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 1,
    enunciado: '11 − 2 = ?',
    alternativas: ['8', '9', '10', '13'],
    resposta_correta: '9',
    dica: 'Tire 1 para chegar no 10. Ainda falta tirar 1: 10 − 1 = 9.',
  },
  {
    id: 'subr_2',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 1,
    enunciado: '12 − 4 = ?',
    alternativas: ['7', '8', '9', '16'],
    resposta_correta: '8',
    dica: 'Tire 2 para chegar no 10. Ainda faltam tirar 2: 10 − 2 = 8.',
  },
  {
    id: 'subr_3',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 1,
    enunciado: '13 − 4 = ?',
    alternativas: ['8', '9', '10', '17'],
    resposta_correta: '9',
    dica: 'Tire 3 para chegar no 10. Ainda falta tirar 1: 10 − 1 = 9.',
  },
  {
    id: 'subr_4',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 2,
    enunciado: '14 − 6 = ?',
    alternativas: ['6', '7', '8', '9'],
    resposta_correta: '8',
    dica: 'Tire 4 para chegar no 10. Ainda faltam tirar 2: 10 − 2 = 8.',
  },
  {
    id: 'subr_5',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 2,
    enunciado: '15 − 7 = ?',
    alternativas: ['7', '8', '9', '10'],
    resposta_correta: '8',
    dica: 'Tire 5 para chegar no 10. Ainda faltam tirar 2: 10 − 2 = 8.',
  },
  {
    id: 'subr_6',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 2,
    enunciado: '16 − 7 = ?',
    alternativas: ['8', '9', '10', '11'],
    resposta_correta: '9',
    dica: 'Tire 6 para chegar no 10. Ainda falta tirar 1: 10 − 1 = 9.',
  },
  {
    id: 'subr_7',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 3,
    enunciado: 'Na festa havia 15 balões e a Rita deu 8 para os amigos. Quantos balões ficaram?',
    alternativas: ['6', '7', '8', '9'],
    resposta_correta: '7',
    dica: 'Tire 5 para chegar no 10. Ainda faltam tirar 3: 10 − 3 = 7.',
  },
  {
    id: 'subr_8',
    habilidade: 'subtracao_com_reagrupamento',
    dificuldade: 3,
    enunciado: 'Lia tinha 14 figurinhas e perdeu 5. Com quantas figurinhas ela ficou?',
    alternativas: ['8', '9', '10', '11'],
    resposta_correta: '9',
    dica: 'Tire 4 para chegar no 10. Ainda falta tirar 1: 10 − 1 = 9.',
  },
];
